name: PellStats
version: '1.0'
main: com.talona.pellStats.PellStats
api-version: '1.21'
author: Talonachris
website: lightning-dev.de

commands:
  pellram:
    description: Shows the current RAM usage
    aliases: psr
    permission: pellstats.ram
  pellcpu:
   description: Shows the CPU usage
   aliases: psc
   permission: pellstats.cpu
  pelltps:
     description: Shows the Server TPS
     aliases: pstps
     permissions: pellstats.tps
  pellstorage:
    description: Shows storage used by the server
    aliases: pss
    permissions: pellstats.storage
  pellinfo:
    description: Shows the Plugin Version
    aliases: psi
  pellgit:
    description: Shows the GitHub Link of the Plugin
    aliases: psgit